# Hardware settings
devices: 2
precision: 16-mixed
accelerator: "auto"
strategy: ddp_find_unused_parameters_true

# Training parameters
max_epochs: 2
gradient_clip_val: 1.0
accumulate_grad_batches: 2
log_every_n_steps: 1
save_dir: "checkpoints"
check_val_every_n_epoch: 1000

# Logging
logger:
  - name: "tensorboard"
    save_dir: "logs"
