IGNORE_INDEX = -100
SAMPLING_RATE = 16000
MAX_LENGTH = 448
GENERATION_MAX_LENGTH = 255

WESTBROOK_DATASET_ACCENT_MAP = {
    0: "dutch",
    1: "german",
    2: "czech",
    3: "polish",
    4: "french",
    5: "hungarian",
    6: "finnish",
    7: "romanian",
    8: "slovak",
    9: "spanish",
    10: "italian",
    11: "estonian",
    12: "lithuanian",
    13: "croatian",
    14: "slovene",
    15: "english",
    16: "scottish",
    17: "irish",
    18: "northernirish",
    19: "indian",
    20: "vietnamese",
    21: "canadian",
    22: "american",
}

ACCENTS = {
    "english": 0,
    "american": 1,
    "scottish": 2,
    "irish": 3,
    "canadian": 4,
    "northernirish": 5,
    "indian": 6,
    "spanish": 7,
    "dutch": 8,
    "german": 9,
    "czech": 10,
    "polish": 11,
    "french": 12,
    "italian": 13,
    "hungarian": 14,
    "finnish": 15,
    "vietnamese": 16,
    "romanian": 17,
    "slovak": 18,
    "estonian": 19,
    "lithuanian": 20,
    "croatian": 21,
    "slovene": 22,
}
